import os
import sys
import json
from typing import List, Literal
from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage, HumanMessage

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))

# Fallback to Gemini for robust structured output to avoid small model issues
from langchain_google_genai import ChatGoogleGenerativeAI
from src.CoreFunctions.StateGraph.state import AgentState

class SubTaskModel(BaseModel):
    id: str = Field(description="A unique identifier for the subtask, e.g., 'task_1'")
    description: str = Field(description="Clear instructions for the worker")
    assigned_worker: Literal[
        "SystemWorker", "GmailWorker", "ProductivityWorker", 
        "MemoryWorker", "ClassroomWorker", "BrowserWorker", "GithubWorker", "MiscWorker"
    ] = Field(
        description="The worker assigned to this task"
    )
    depends_on: List[str] = Field(
        default_factory=list,
        description="List of subtask IDs that must complete before this task can execute. If completely independent, leave empty."
    )

class TaskPlan(BaseModel):
    subtasks: List[SubTaskModel] = Field(description="List of subtasks and their operational dependency graph")

ROUTER_PROMPT = """
You are the Task Router. Your job is to decompose the user's mega-prompt into isolated sub-tasks with a clear dependency structure.
Available workers:
- GmailWorker: Reads, searches, and sends emails.
- ClassroomWorker: Manages Google Classroom courses, coursework, assignments, and announcements.
- ProductivityWorker: Calendar events, Google Tasks, Weather.
- MemoryWorker: Long-term memory storage and retrieval.
- SystemWorker: OS terminal commands, file management, scripts, system health.
- BrowserWorker: Navigates websites, searches information, logs in, clicks elements, and automates online tasks using accessibility trees without screenshots.
- GithubWorker: Interfaces with GitHub API to retrieve account profile details, list repositories, track recent public and private events/activity, inspect repository file contents and directories, and search code across repositories.
- MiscWorker: General-purpose worker that handles miscellaneous API integrations (such as using ytmusicapi to manage playlists or retrieve library tracks), complex calculations, custom scripts, or general utility work that does not fit into other specialized workers.

RULES & WORKFLOW FOR SPECIALIZED TASKS:
1. Break down the request into the smallest logical steps.
2. Assign each step to the correct worker.
3. Determine the dependencies between tasks:
   - If task B requires data, notes, or files generated by task A, then task B MUST depend on task A (e.g. `depends_on = ["task_1"]`).
   - If tasks can be run in parallel concurrently because they are independent (e.g., checking system stats AND checking unread emails), leave the `depends_on` list EMPTY.
4. **Browser/Web Automation Workflow**:
   - Web automation sessions (e.g. navigating to a website, searching, clicking, logging in, or playing media) MUST be kept as a single, combined subtask assigned to BrowserWorker.
   - Do NOT break a single web session into multiple sequential BrowserWorker subtasks (e.g. step 1 navigate, step 2 search, step 3 click), because the browser page state and context are lost between different worker runs. Keep them combined in one subtask description (e.g., 'Navigate to music.youtube.com, search for j-pop, and play the first result').
5. **Media Control / Music Playback Workflow**:
   - Any requests to control playback (play, pause, toggle, next, previous, status check) for Spotify or YouTube Music should be routed to SystemWorker. SystemWorker must run the local helper python scripts using the project's virtual environment interpreter (e.g. `.venv/bin/python3 Skills/media-control/youtube-music-control/scripts/youtube_music_control.py` or `.venv/bin/python3 Skills/media-control/spotify-playback-control/scripts/spotify_playback_control.py`) to execute these actions. Do NOT use system `python3` or try to install packages.
6. **Miscellaneous API & Playlist Management**:
   - Any requests to manage playlists (creating, adding songs, removing songs, listing library/favorite songs) on YouTube Music or other APIs should be routed to MiscWorker. MiscWorker can run custom background API scripts or libraries (like `ytmusicapi`) to complete these commands instantly.
7. **Local File System Access & File Management**:
   - Only SystemWorker has permission and tools to access the local file system. This includes creating/deleting directories, creating/updating files, downloading files to disk, reading file contents, listing folders/directories, and executing terminal commands.
   - All other workers (BrowserWorker, GmailWorker, ClassroomWorker, GithubWorker, ProductivityWorker, MemoryWorker, MiscWorker) DO NOT have direct access to the local filesystem.
   - If a request requires retrieving or generating data from any external source (e.g., scraping web contents, fetching Gmail attachments, downloading Classroom materials) and saving/downloading that content to the local disk, you MUST split it into sequential subtasks:
     - The first task (assigned to the retrieving worker, e.g., BrowserWorker, GmailWorker, ClassroomWorker, etc.): Retrieve/fetch the data or content.
     - The second task (assigned to SystemWorker, which MUST depend on the first task): Write/save that content, create local directories, or download the files to the local file system using the retrieved data.
   - If a request requires accessing or reading a local file to process it with another worker, you MUST split it into:
     - The first task (assigned to SystemWorker): Read the file contents from the local file system.
     - The second task (assigned to the processing worker, e.g., GmailWorker, BrowserWorker, etc., depending on the SystemWorker read task): Process the read content.
8. **Handling Long Data /  Bulk Content**:
   - For long content, bulk data, or text drafts (such as multiple LinkedIn posts, long essays, or large lists of URLs/emails):
     - DO NOT pass the entire raw text/content directly inside the subtask descriptions or working memory text variables, as it can cause model context bloating or truncation.
     - Instead, decompose the tasks to save/store the content in a local workspace file (e.g., a markdown draft, JSON file, or CSV under a `Memory/` or local directory) using SystemWorker.
     - Pass only the reference file path (e.g., `file_path: "/home/prit/.../linkedin_posts.json"`) between workers in the description or working_memory keys.
     - Instruct subsequent workers to read, modify, or publish directly from that file path.
"""

def task_router_node(state: AgentState):
    from src.CoreFunctions.logger import log_node_start, log_node_end, log_message
    log_node_start("TaskRouter", state)
    
    print("\n[Node: Task Router] Analyzing request...")
    primary_goal = state.get("primary_goal", "")
    working_memory = state.get("working_memory", {}) or {}
    chat_history = state.get("chat_history", []) or []
    
    user_profile = working_memory.get("user_profile", {})
    relevant_memories = working_memory.get("relevant_memories", [])
    
    # 1. Build conversational history
    history_str = ""
    if chat_history:
        history_str = "Conversation History:\n"
        for msg in chat_history:
            history_str += f"- {msg['role'].capitalize()}: {msg['content']}\n"
            
    # 2. Build user context profile
    context_str = ""
    if user_profile:
        context_str += f"User Profile Details: {json.dumps(user_profile)}\n"
    if relevant_memories:
        context_str += "Relevant Stored Memories / Past Facts:\n"
        for mem in relevant_memories:
            context_str += f"- {mem}\n"
            
    # Include details of any task failures/roadblocks requesting re-planning
    replan_context = working_memory.get("replan_context")
    if replan_context:
        context_str += f"\n[REPLAN REQUEST CONTEXT - PREVIOUS ATTEMPT WORKFLOW FAILED]\n{replan_context}\n"
            
    input_content = f"User Request: {primary_goal}\n"
    if context_str:
        input_content = f"Injected Context:\n{context_str}\n\n" + input_content
    if history_str:
        input_content = history_str + "\n" + input_content
    
    # Use a robust model for structured JSON parsing
    model_name = "gemini-3.1-flash-lite"
    log_message(f"TaskRouter: Invoking model {model_name} for structured task planning.")
    
    llm = ChatGoogleGenerativeAI(model=model_name, temperature=0)
    structured_llm = llm.with_structured_output(TaskPlan)
    
    plan: TaskPlan = structured_llm.invoke([
        SystemMessage(content=ROUTER_PROMPT),
        HumanMessage(content=input_content)
    ])
    
    active_subtasks = []
    for st in plan.subtasks:
        active_subtasks.append({
            "id": st.id,
            "description": st.description,
            "assigned_worker": st.assigned_worker,
            "status": "pending",
            "depends_on": st.depends_on or []
        })
        print(f"  -> Created Subtask: {st.id} ({st.assigned_worker}) | Depends on: {st.depends_on or []}")
        
    output_state = {
        "active_subtasks": active_subtasks,
        "working_memory": working_memory,
        "completed_tasks": {}
    }
    
    log_node_end("TaskRouter", output_state)
    return output_state

