import os
import sys
import json
from typing import List, Literal
from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage, HumanMessage

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))

# Fallback to Gemini for robust structured output to avoid small model issues
from langchain_google_genai import ChatGoogleGenerativeAI
from src.CoreFunctions.StateGraph.state import AgentState

class SubTaskModel(BaseModel):
    id: str = Field(description="A unique identifier for the subtask, e.g., 'task_1'")
    description: str = Field(description="Clear instructions for the worker")
    assigned_worker: Literal[
        "SystemWorker", "GmailWorker", "ProductivityWorker", 
        "MemoryWorker", "ClassroomWorker", "ObsidianWorker", "BrowserWorker"
    ] = Field(
        description="The worker assigned to this task"
    )
    depends_on: List[str] = Field(
        default_factory=list,
        description="List of subtask IDs that must complete before this task can execute. If completely independent, leave empty."
    )

class TaskPlan(BaseModel):
    subtasks: List[SubTaskModel] = Field(description="List of subtasks and their operational dependency graph")

ROUTER_PROMPT = """
You are the Task Router. Your job is to decompose the user's mega-prompt into isolated sub-tasks with a clear dependency structure.
Available workers:
- GmailWorker: Reads, searches, and sends emails.
- ClassroomWorker: Manages Google Classroom courses, coursework, assignments, and announcements.
- ProductivityWorker: Calendar events, Google Tasks, Weather.
- MemoryWorker: Long-term memory storage and retrieval.
- SystemWorker: OS terminal commands, file management, scripts, system health.
- ObsidianWorker: Creates, refactors, and organizes structured Obsidian notes (.md files) and designs infinite whiteboard mind-maps and visual dashboards (.canvas files).
- BrowserWorker: Navigates websites, searches information, logs in, clicks elements, and automates online tasks using accessibility trees without screenshots.

RULES & WORKFLOW FOR SPECIALIZED TASKS:
1. Break down the request into the smallest logical steps.
2. Assign each step to the correct worker.
3. Determine the dependencies between tasks:
   - If task B requires data, notes, or files generated by task A, then task B MUST depend on task A (e.g. `depends_on = ["task_1"]`).
   - If tasks can be run in parallel concurrently because they are independent (e.g., checking system stats AND checking unread emails), leave the `depends_on` list EMPTY.
4. **Classroom Coursework Canvas Visualizer Workflow**:
   - Step 1: Use `ClassroomWorker` to list courses and fetch active assignments/coursework (no dependencies).
   - Step 2: Use `ObsidianWorker` to compile this data, create structured markdown notes for the coursework/assignments inside the vault under the 'Academic/' folder, and then create or update a beautiful Obsidian Canvas (.canvas) visualizing these courses, assignment files, deadlines, and flow edges using the Coordinate Mapping Layout Algorithm. This task depends on the ClassroomWorker task.
5. When creating connected structures (folders or multiple notes) in Obsidian, explicitly state the exact target note names in the description of subsequent subtasks (e.g. 'including a wikilink [[Prithvi_Dashboard]] back to the dashboard created in task_1') to ensure perfect bidirectional linking context between independent worker runs.
6. **Browser/Web Automation Workflow**:
   - Web automation sessions (e.g. navigating to a website, searching, clicking, logging in, or playing media) MUST be kept as a single, combined subtask assigned to BrowserWorker.
   - Do NOT break a single web session into multiple sequential BrowserWorker subtasks (e.g. step 1 navigate, step 2 search, step 3 click), because the browser page state and context are lost between different worker runs. Keep them combined in one subtask description (e.g., 'Navigate to music.youtube.com, search for j-pop, and play the first result').
"""

def task_router_node(state: AgentState):
    print("\n[Node: Task Router] Analyzing request...")
    primary_goal = state.get("primary_goal", "")
    working_memory = state.get("working_memory", {}) or {}
    chat_history = state.get("chat_history", []) or []
    
    user_profile = working_memory.get("user_profile", {})
    relevant_memories = working_memory.get("relevant_memories", [])
    
    # 1. Build conversational history
    history_str = ""
    if chat_history:
        history_str = "Conversation History:\n"
        for msg in chat_history:
            history_str += f"- {msg['role'].capitalize()}: {msg['content']}\n"
            
    # 2. Build user context profile
    context_str = ""
    if user_profile:
        context_str += f"User Profile Details: {json.dumps(user_profile)}\n"
    if relevant_memories:
        context_str += "Relevant Stored Memories / Past Facts:\n"
        for mem in relevant_memories:
            context_str += f"- {mem}\n"
            
    input_content = f"User Request: {primary_goal}\n"
    if context_str:
        input_content = f"Injected Context:\n{context_str}\n\n" + input_content
    if history_str:
        input_content = history_str + "\n" + input_content
    
    # Use a robust model for structured JSON parsing
    llm = ChatGoogleGenerativeAI(model="gemini-3.1-flash-lite", temperature=0)
    structured_llm = llm.with_structured_output(TaskPlan)
    
    plan: TaskPlan = structured_llm.invoke([
        SystemMessage(content=ROUTER_PROMPT),
        HumanMessage(content=input_content)
    ])
    
    active_subtasks = []
    for st in plan.subtasks:
        active_subtasks.append({
            "id": st.id,
            "description": st.description,
            "assigned_worker": st.assigned_worker,
            "status": "pending",
            "depends_on": st.depends_on or []
        })
        print(f"  -> Created Subtask: {st.id} ({st.assigned_worker}) | Depends on: {st.depends_on or []}")
        
    return {
        "active_subtasks": active_subtasks,
        "working_memory": working_memory,
        "completed_tasks": {}
    }

