import os
import sys
import json
from typing import List
from enum import Enum
from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage, HumanMessage
from src.CoreFunctions.StateGraph.state import AgentState

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))

# Load registry and force decorator execution by scanning workers directory
from src.CoreFunctions.StateGraph.registry import WorkerRegistry, scan_and_register_workers
scan_and_register_workers()

class SubTaskModel(BaseModel):
    id: str = Field(description="A unique identifier for the subtask, e.g., 'task_1'")
    description: str = Field(description="Clear instructions for the worker")
    assigned_worker: str = Field(
        description="The worker assigned to this task. Must be one of the active worker names listed in the system prompt."
    )
    depends_on: List[str] = Field(
        default_factory=list,
        description="List of subtask IDs that must complete before this task can execute. If completely independent, leave empty."
    )

class TaskPlan(BaseModel):
    subtasks: List[SubTaskModel] = Field(description="List of subtasks and their operational dependency graph")

def get_router_prompt() -> str:
    worker_descriptions = []
    dynamic_rules = []
    
    for name, worker in WorkerRegistry.get_all_workers().items():
        if worker.is_graph_node:
            worker_descriptions.append(f"- {worker.name}: {worker.description}")
            if hasattr(worker, "routing_rules") and worker.routing_rules:
                dynamic_rules.extend(worker.routing_rules)
            
    workers_list_str = "\n".join(worker_descriptions)
    
    base_rules_before = [
        "Break down the request into the smallest logical steps.",
        "Assign each step to the correct worker.",
        "Determine the dependencies between tasks:\n   - If task B requires data, notes, or files generated by task A, then task B MUST depend on task A (e.g. `depends_on = [\"task_1\"]`).\n   - If tasks can be run in parallel concurrently because they are independent (e.g., checking system stats AND checking unread emails), leave the `depends_on` list EMPTY."
    ]
    
    base_rules_after = [
        "**Handling Long Data / Bulk Content**:\n   - For long content, bulk data, or text drafts (such as multiple LinkedIn posts, long essays, or large lists of URLs/emails):\n     - DO NOT pass the entire raw text/content directly inside the subtask descriptions or working memory text variables, as it can cause model context bloating or truncation.\n     - Instead, decompose the tasks to save/store the content in a local workspace file (e.g., a markdown draft, JSON file, or CSV under a `Memory/` or local directory) using SystemWorker.\n     - Pass only the reference file path (e.g., `file_path: \"/home/prit/.../linkedin_posts.json\"`) between workers in the description or working_memory keys.\n     - Instruct subsequent workers to read, modify, or publish directly from that file path."
    ]
    
    all_rules = base_rules_before + dynamic_rules + base_rules_after
    rules_formatted = []
    for idx, rule in enumerate(all_rules, 1):
        rules_formatted.append(f"{idx}. {rule}")
        
    rules_str = "\n".join(rules_formatted)
    
    return f"""You are the Task Router. Your job is to decompose the user's mega-prompt into isolated sub-tasks with a clear dependency structure.

CRITICAL INSTRUCTION: You MUST ONLY assign tasks to the workers listed under 'Available workers' below. Under NO circumstances should you route to a worker that is not currently listed, even if they are mentioned in the conversation history or in the user's current request. If the user asks to perform an action using a worker that is not listed, do not schedule any subtask for that action.

Available workers:
{workers_list_str}

RULES & WORKFLOW FOR SPECIALIZED TASKS:
{rules_str}
"""

def task_router_node(state: AgentState):
    from src.CoreFunctions.Infrastructure.logger import log_node_start, log_node_end, log_message
    log_node_start("TaskRouter", state)
    
    print("\n[Node: Task Router] Analyzing request...")
    primary_goal = state.get("primary_goal", "")
    working_memory = state.get("working_memory", {}) or {}
    chat_history = state.get("chat_history", []) or []
    
    user_profile = working_memory.get("user_profile", {})
    relevant_memories = working_memory.get("relevant_memories", [])
    
    # 1. Build conversational history
    history_str = ""
    if chat_history:
        history_str = "Conversation History:\n"
        for msg in chat_history:
            history_str += f"- {msg['role'].capitalize()}: {msg['content']}\n"
            
    # 2. Build user context profile
    context_str = ""
    if user_profile:
        context_str += f"User Profile Details: {json.dumps(user_profile)}\n"
    if relevant_memories:
        context_str += "Relevant Stored Memories / Past Facts:\n"
        for mem in relevant_memories:
            context_str += f"- {mem}\n"
            
    # Include details of any task failures/roadblocks requesting re-planning
    replan_context = working_memory.get("replan_context")
    if replan_context:
        context_str += f"\n[REPLAN REQUEST CONTEXT - PREVIOUS ATTEMPT WORKFLOW FAILED]\n{replan_context}\n"
            
    input_content = f"User Request: {primary_goal}\n"
    if context_str:
        input_content = f"Injected Context:\n{context_str}\n\n" + input_content
    if history_str:
        input_content = history_str + "\n" + input_content
    
    # Use a robust model for structured JSON parsing
    from langchain_google_genai import ChatGoogleGenerativeAI
    model_name = "gemini-3.1-flash-lite"
    log_message(f"TaskRouter: Invoking model {model_name} for structured task planning.")
    
    llm = ChatGoogleGenerativeAI(model=model_name, temperature=0)
    structured_llm = llm.with_structured_output(TaskPlan)
    
    try:
        plan: TaskPlan = structured_llm.invoke([
            SystemMessage(content=get_router_prompt()),
            HumanMessage(content=input_content)
        ])
    except Exception as e:
        print(f"  ⚠️ Task Router parsing/validation error: {e}. Retrying with error details...")
        log_message(f"TaskRouter validation failed: {e}. Executing self-correction retry.")
        
        error_context = f"""
Previous attempt failed validation/parsing with the following error:
{str(e)}

Please correct the JSON formatting, ensure all worker assignments are strictly from the 'Available workers' list, and try again.
"""
        try:
            plan: TaskPlan = structured_llm.invoke([
                SystemMessage(content=get_router_prompt()),
                HumanMessage(content=input_content),
                SystemMessage(content=error_context)
            ])
        except Exception as retry_err:
            print(f"  ❌ Task Router failed self-correction retry: {retry_err}. Falling back to default execution node.")
            log_message(f"TaskRouter retry failed: {retry_err}. Activating fallback routing.")
            plan = TaskPlan(subtasks=[
                SubTaskModel(
                    id="fallback_task",
                    description=f"Fallback execution of user request: {primary_goal}",
                    assigned_worker="MiscWorker",
                    depends_on=[]
                )
            ])

    active_subtasks = []
    active_names = WorkerRegistry.get_worker_names()
    completed_tasks = state.get("completed_tasks", {}) or {}
    
    for st in plan.subtasks:
        worker_name_str = st.assigned_worker.strip()
        status = "pending"
        if worker_name_str not in active_names:
            print(f"  ⚠️ Warning: Task Router assigned task to '{worker_name_str}' which is currently inactive or unregistered.")
            status = "failed"
            completed_tasks[st.id] = f"Error: Worker '{worker_name_str}' is currently inactive or unregistered."
            
        active_subtasks.append({
            "id": st.id,
            "description": st.description,
            "assigned_worker": worker_name_str,
            "status": status,
            "depends_on": st.depends_on or []
        })
        print(f"  -> Created Subtask: {st.id} ({worker_name_str}) | Depends on: {st.depends_on or []} | Status: {status}")
        
    output_state = {
        "active_subtasks": active_subtasks,
        "working_memory": working_memory,
        "completed_tasks": completed_tasks
    }
    
    log_node_end("TaskRouter", output_state)
    return output_state

