from langchain_core.tools import StructuredTool
from .browser_manager import _get_browser_page, _get_elements_formatted
import os

def _get_local_llm():
    try:
        from langchain_ollama import ChatOllama
        return ChatOllama(
            model=os.getenv("OLLAMA_MODEL", "gemma4:e4b"),
            temperature=0
        )
    except Exception:
        return None

async def browser_read_current_page(offset: int = 0, limit: int = 30) -> str:
    """Reads the current active tab's URL, page title, and interactive elements without navigating.
    
    Args:
        offset (int): Starting index of interactive elements to list (for pagination). Defaults to 0.
        limit (int): Maximum number of interactive elements to return. Defaults to 30.
    """
    print(f"\n[DEBUG] 🛠️ Calling Tool: browser_read_current_page")
    try:
        page = await _get_browser_page()
        url = page.url
        title = await page.title()
        elements_str = await _get_elements_formatted(offset=offset, limit=limit)
        print(f"Current Page Title: {title}\nCurrent Page URL: {url}\n\nInteractive Elements:\n{elements_str}")
        return f"Current Page Title: {title}\nCurrent Page URL: {url}\n\nInteractive Elements:\n{elements_str}"
    except Exception as e:
        return f"Error reading current page: {e}"

async def browser_read_page_content(mode: str = "summary", query: str = None, chunk_index: int = 0) -> str:
    """Reads or queries the textual content (paragraphs, headings, articles) of the current active browser tab.
    
    Args:
        mode (str): The reading mode:
            - 'summary': Uses a local model to summarize the main content of the page. Recommended for long pages.
            - 'query': Uses a local model to answer a specific question ('query') based on the page content.
            - 'chunk': Returns a specific paragraph/text chunk of the page (specified by 'chunk_index') to keep context small.
            - 'metadata': Returns title, URL, and a quick snippet.
        query (str, optional): The question to answer about the page content (only used when mode='query').
        chunk_index (int): The zero-based index of the text chunk to retrieve (only used when mode='chunk'). Each chunk is roughly 1500 words.
    """
    print(f"\n[DEBUG] 🛠️ Calling Tool: browser_read_page_content")
    print(f"   Args: mode={mode}, query={query}, chunk_index={chunk_index}")
    try:
        page = await _get_browser_page()
        url = page.url
        title = await page.title()
        
        script = """
        () => {
            const elements = document.querySelectorAll('p, h1, h2, h3, h4, h5, h6, li, article, section');
            const texts = [];
            elements.forEach(el => {
                if (el.closest('nav') || el.closest('footer') || el.closest('header') || el.closest('script') || el.closest('style')) {
                    return;
                }
                const text = el.innerText.trim();
                if (text && text.length > 20) {
                    texts.push(text);
                }
            });
            return texts.join('\\n\\n');
        }
        """
        full_text = await page.evaluate(script)
        if not full_text:
            return f"Page Title: {title}\nURL: {url}\nNo readable text content found on this page."
            
        words = full_text.split()
        chunk_size = 1500
        total_chunks = (len(words) + chunk_size - 1) // chunk_size
        
        if mode == "metadata":
            snippet = " ".join(words[:100])
            return f"Title: {title}\nURL: {url}\nTotal Words: {len(words)}\nTotal Chunks: {total_chunks}\nSnippet: {snippet}..."
            
        elif mode == "chunk":
            if chunk_index < 0 or chunk_index >= total_chunks:
                return f"Error: chunk_index {chunk_index} is out of range. Total chunks available: {total_chunks}."
            start_word = chunk_index * chunk_size
            end_word = start_word + chunk_size
            chunk_text = " ".join(words[start_word:end_word])
            return f"Chunk {chunk_index + 1}/{total_chunks} of page content (Title: {title}, URL: {url}):\n\n{chunk_text}"
            
        elif mode == "summary":
            local_llm = _get_local_llm()
            if not local_llm:
                chunk_text = " ".join(words[:chunk_size])
                return f"[Local LLM not available. Returning first chunk of {total_chunks} chunks] Page Content:\n\n{chunk_text}"
                
            prompt = f"Summarize the following text content from the webpage '{title}' ({url}) concisely, extracting the key points and main arguments:\n\n{full_text[:12000]}"
            try:
                response = await local_llm.ainvoke(prompt)
                return f"Summary of the webpage '{title}' (generated by local model):\n\n{response.content}"
            except Exception as e:
                chunk_text = " ".join(words[:chunk_size])
                return f"[Local LLM error: {e}. Returning first chunk of {total_chunks} chunks] Page Content:\n\n{chunk_text}"
                
        elif mode == "query":
            if not query:
                return "Error: mode='query' requires a 'query' argument."
            local_llm = _get_local_llm()
            if not local_llm:
                chunk_text = " ".join(words[:chunk_size])
                return f"[Local LLM not available. Returning first chunk for manual query: '{query}'] Page Content:\n\n{chunk_text}"
                
            prompt = f"Based on the following text content from the webpage '{title}', answer this question: '{query}'. Provide a concise and accurate answer based only on the text.\n\nContent:\n{full_text[:12000]}"
            try:
                response = await local_llm.ainvoke(prompt)
                return f"Answer (generated by local model): {response.content}"
            except Exception as e:
                chunk_text = " ".join(words[:chunk_size])
                return f"[Local LLM error: {e}. Returning first chunk for manual search: '{query}'] Page Content:\n\n{chunk_text}"
        else:
            return f"Error: Invalid mode '{mode}'."
    except Exception as e:
        return f"Error extracting page text content: {e}"

async def browser_go_back(offset: int = 0, limit: int = 30) -> str:
    """Navigates back to the previous page in the browser history.

    Args:
        offset (int): Starting index of interactive elements to list. Defaults to 0.
        limit (int): Maximum number of interactive elements to return. Defaults to 30.
    """
    print(f"\n[DEBUG] 🛠️ Calling Tool: browser_go_back")
    try:
        page = await _get_browser_page()
        await page.go_back(timeout=10000)
        try:
            await page.wait_for_load_state("networkidle", timeout=4000)
        except Exception:
            pass
        await page.wait_for_timeout(2000)
        elements_str = await _get_elements_formatted(offset=offset, limit=limit)
        return elements_str
    except Exception as e:
        return f"Error going back: {e}"

browser_read_current_page_tool = StructuredTool.from_function(
    func=browser_read_current_page,
    name="browser_read_current_page",
    coroutine=browser_read_current_page,
    description="Read the current active tab's URL, page title, and interactive elements"
)

browser_read_page_content_tool = StructuredTool.from_function(
    func=browser_read_page_content,
    name="browser_read_page_content",
    coroutine=browser_read_page_content,
    description="Read or query the textual content of the current page in chunks or using a local LLM"
)

browser_go_back_tool = StructuredTool.from_function(
    func=browser_go_back,
    name="browser_go_back",
    coroutine=browser_go_back,
    description="Navigate back to the previous page"
)
