version: "3"

services:
  waha:
    image: devlikeapro/waha
    restart: unless-stopped
    ports:
      - "8085:3000"
    env_file:
      - .env
    environment:
      # This overrides whatever is in your .env file
      - WHATSAPP_DEFAULT_ENGINE=NOWEB
    volumes:
      - ./waha-data:/app/data